spring:
  batch:
    job:
      names: ${job.name:chunkJob-2}
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: samuel4526
  jpa:
    show-sql: true